id: P000479
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG03678
  title: རྫོང་ཁའི་གཏམ་རྒྱུད་སྣ་ཚོགས་དཔེ་ཆ་གསུམ་པ་
  author: ''
  volumes:
    b3a3fdc546a94e39b3fb112b5138b1d4:
      image_group_id: I00KG03762
      title: Volume 1 of rdzong kha'i gtam rgyud sna tshogs dpe cha gsum pa
      volume_number: 1
      total_pages: 278
      base_file: v001.txt
